/**
 * PDF plan generator — produces A1/A3/A4 floor plans with HF title block.
 * Uses pdf-lib for generation.
 */

import { PDFDocument, StandardFonts, rgb, PDFPage, PDFFont } from "pdf-lib";
import type { SurveyWall, ExportOptions } from "./types";
import { calculateLayout } from "./planRenderer";

const HF_BLUE = rgb(0, 0.337, 0.655); // #0056a7
const DARK = rgb(0.165, 0.165, 0.165);
const GRAY = rgb(0.4, 0.4, 0.4);
const LIGHT_GRAY = rgb(0.9, 0.9, 0.9);
const WHITE = rgb(1, 1, 1);

// mm to PDF points (1mm = 2.835pt)
const MM = 2.835;

export async function generatePlanPdf(
  walls: SurveyWall[],
  options: ExportOptions
): Promise<Uint8Array> {
  const layout = calculateLayout(walls, options);
  const doc = await PDFDocument.create();
  const fontRegular = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = layout.paperWidth * MM;
  const pageHeight = layout.paperHeight * MM;
  const page = doc.addPage([pageWidth, pageHeight]);

  // Background
  page.drawRectangle({
    x: 0, y: 0,
    width: pageWidth, height: pageHeight,
    color: WHITE,
  });

  // Border
  page.drawRectangle({
    x: 5 * MM, y: 5 * MM,
    width: pageWidth - 10 * MM,
    height: pageHeight - 10 * MM,
    borderColor: DARK,
    borderWidth: 0.5,
  });

  // Draw walls
  for (const w of layout.walls) {
    page.drawLine({
      start: { x: w.x1 * MM, y: w.y1 * MM },
      end: { x: w.x2 * MM, y: w.y2 * MM },
      thickness: 1.5,
      color: DARK,
    });
  }

  // Draw dimensions
  for (const d of layout.dimensions) {
    page.drawLine({
      start: { x: d.x1 * MM, y: d.y1 * MM },
      end: { x: d.x2 * MM, y: d.y2 * MM },
      thickness: 0.3,
      color: GRAY,
    });

    const midX = ((d.x1 + d.x2) / 2) * MM;
    const midY = ((d.y1 + d.y2) / 2) * MM;
    page.drawText(d.label, {
      x: midX - fontRegular.widthOfTextAtSize(d.label, 6) / 2,
      y: midY + 1.5,
      size: 6,
      font: fontRegular,
      color: GRAY,
    });
  }

  // Grid lines (light reference grid)
  drawGrid(page, layout, fontRegular);

  // Title block
  drawTitleBlock(page, layout, options, fontRegular, fontBold);

  // North arrow
  drawNorthArrow(page, layout, fontBold);

  // Scale bar
  drawScaleBar(page, layout, options, fontRegular);

  return doc.save();
}

function drawTitleBlock(
  page: PDFPage,
  layout: { paperWidth: number; paperHeight: number; scale: number },
  options: ExportOptions,
  fontRegular: PDFFont,
  fontBold: PDFFont
) {
  const tbWidth = layout.paperWidth - 30;
  const tbHeight = 35;
  const tbX = 15 * MM;
  const tbY = 10 * MM;

  // Title block background
  page.drawRectangle({
    x: tbX, y: tbY,
    width: tbWidth * MM, height: tbHeight * MM,
    color: rgb(0.98, 0.98, 0.97),
    borderColor: DARK,
    borderWidth: 0.5,
  });

  // HF Blue accent bar
  page.drawRectangle({
    x: tbX, y: tbY + (tbHeight - 2) * MM,
    width: tbWidth * MM, height: 2 * MM,
    color: HF_BLUE,
  });

  // Company name
  page.drawText("HARMONY FIRE", {
    x: tbX + 5 * MM,
    y: tbY + (tbHeight - 8) * MM,
    size: 14,
    font: fontBold,
    color: HF_BLUE,
  });

  page.drawText("Fire Protection Specialists", {
    x: tbX + 5 * MM,
    y: tbY + (tbHeight - 13) * MM,
    size: 7,
    font: fontRegular,
    color: GRAY,
  });

  // Plan details
  const detailX = tbX + (tbWidth * 0.4) * MM;
  const details = [
    { label: "Plan Ref", value: options.plan_reference },
    { label: "Floor", value: options.floor_label },
    { label: "Scale", value: options.scale },
    { label: "Paper", value: options.paper_size },
  ];

  let dy = 0;
  for (const d of details) {
    page.drawText(`${d.label}:`, {
      x: detailX,
      y: tbY + (tbHeight - 8 - dy) * MM,
      size: 7,
      font: fontBold,
      color: DARK,
    });
    page.drawText(d.value, {
      x: detailX + 25 * MM,
      y: tbY + (tbHeight - 8 - dy) * MM,
      size: 7,
      font: fontRegular,
      color: DARK,
    });
    dy += 5;
  }

  // Project + date
  const rightX = tbX + (tbWidth * 0.75) * MM;
  if (options.project_name) {
    page.drawText("Project:", {
      x: rightX, y: tbY + (tbHeight - 8) * MM,
      size: 7, font: fontBold, color: DARK,
    });
    page.drawText(options.project_name, {
      x: rightX + 20 * MM, y: tbY + (tbHeight - 8) * MM,
      size: 7, font: fontRegular, color: DARK,
    });
  }

  page.drawText("Date:", {
    x: rightX, y: tbY + (tbHeight - 13) * MM,
    size: 7, font: fontBold, color: DARK,
  });
  page.drawText(new Date().toLocaleDateString("en-GB"), {
    x: rightX + 20 * MM, y: tbY + (tbHeight - 13) * MM,
    size: 7, font: fontRegular, color: DARK,
  });

  page.drawText("Generated by hf.bluebook", {
    x: rightX, y: tbY + (tbHeight - 28) * MM,
    size: 6, font: fontRegular, color: GRAY,
  });
}

function drawGrid(
  page: PDFPage,
  layout: { paperWidth: number; paperHeight: number; scale: number; offsetX: number; offsetY: number },
  _fontRegular: PDFFont
) {
  const gridSpacing = 1000 / layout.scale;
  const drawableStartX = 15 * MM;
  const drawableStartY = 50 * MM;
  const drawableEndX = (layout.paperWidth - 15) * MM;
  const drawableEndY = (layout.paperHeight - 15) * MM;

  if (gridSpacing < 5) return;

  for (let x = layout.offsetX; x * MM < drawableEndX; x += gridSpacing) {
    if (x * MM < drawableStartX) continue;
    page.drawLine({
      start: { x: x * MM, y: drawableStartY },
      end: { x: x * MM, y: drawableEndY },
      thickness: 0.1,
      color: LIGHT_GRAY,
    });
  }

  for (let y = layout.offsetY; y * MM < drawableEndY; y += gridSpacing) {
    if (y * MM < drawableStartY) continue;
    page.drawLine({
      start: { x: drawableStartX, y: y * MM },
      end: { x: drawableEndX, y: y * MM },
      thickness: 0.1,
      color: LIGHT_GRAY,
    });
  }
}

function drawNorthArrow(
  page: PDFPage,
  layout: { paperWidth: number; paperHeight: number },
  fontBold: PDFFont
) {
  const cx = (layout.paperWidth - 25) * MM;
  const cy = (layout.paperHeight - 25) * MM;
  const size = 8 * MM;

  page.drawLine({
    start: { x: cx, y: cy - size / 2 },
    end: { x: cx, y: cy + size / 2 },
    thickness: 1.5,
    color: DARK,
  });

  page.drawLine({
    start: { x: cx - 2 * MM, y: cy + size / 2 - 3 * MM },
    end: { x: cx, y: cy + size / 2 },
    thickness: 1.5,
    color: DARK,
  });
  page.drawLine({
    start: { x: cx + 2 * MM, y: cy + size / 2 - 3 * MM },
    end: { x: cx, y: cy + size / 2 },
    thickness: 1.5,
    color: DARK,
  });

  page.drawText("N", {
    x: cx - 3,
    y: cy + size / 2 + 2 * MM,
    size: 10,
    font: fontBold,
    color: DARK,
  });
}

function drawScaleBar(
  page: PDFPage,
  layout: { paperWidth: number; paperHeight: number; scale: number },
  options: ExportOptions,
  fontRegular: PDFFont
) {
  const barLength = (5000 / layout.scale) * MM;
  const x = 20 * MM;
  const y = 52 * MM;

  page.drawLine({
    start: { x, y },
    end: { x: x + barLength, y },
    thickness: 1,
    color: DARK,
  });

  page.drawLine({ start: { x, y: y - 2 * MM }, end: { x, y: y + 2 * MM }, thickness: 0.5, color: DARK });
  page.drawLine({ start: { x: x + barLength, y: y - 2 * MM }, end: { x: x + barLength, y: y + 2 * MM }, thickness: 0.5, color: DARK });

  page.drawText("0", { x: x - 2, y: y - 5 * MM, size: 6, font: fontRegular, color: DARK });
  page.drawText("5m", { x: x + barLength - 4, y: y - 5 * MM, size: 6, font: fontRegular, color: DARK });
  page.drawText(options.scale, { x: x + barLength / 2 - 5, y: y + 3 * MM, size: 7, font: fontRegular, color: GRAY });
}
