/**
 * DXF exporter — generates DXF floor plans with HF layers.
 * Uses @tarikjabiri/dxf for DXF file generation.
 * Layers: HF-WALLS, HF-DIMS, HF-GRID, HF-TEXT, HF-TITLEBLOCK
 */

import { DxfWriter } from "@tarikjabiri/dxf";
import type { SurveyWall, ExportOptions } from "./types";
import { calculateLayout } from "./planRenderer";

function pt(x: number, y: number) {
  return { x, y, z: 0 };
}

// HF Blue in ACI (AutoCAD Color Index) — closest to #0056a7 is ACI 150
const HF_BLUE_ACI = 150;
const WHITE_ACI = 7;
const GRAY_ACI = 8;
const DARK_ACI = 250;

export function generatePlanDxf(
  walls: SurveyWall[],
  options: ExportOptions
): string {
  const layout = calculateLayout(walls, options);
  const dxf = new DxfWriter();

  // Add layers
  dxf.addLayer("HF-WALLS", WHITE_ACI, "CONTINUOUS");
  dxf.addLayer("HF-DIMS", GRAY_ACI, "CONTINUOUS");
  dxf.addLayer("HF-GRID", DARK_ACI, "CONTINUOUS");
  dxf.addLayer("HF-TEXT", WHITE_ACI, "CONTINUOUS");
  dxf.addLayer("HF-TITLEBLOCK", HF_BLUE_ACI, "CONTINUOUS");

  // Draw walls on HF-WALLS layer
  dxf.setCurrentLayerName("HF-WALLS");
  for (const w of layout.walls) {
    dxf.addLine(pt(w.x1, w.y1), pt(w.x2, w.y2));
  }

  // Draw dimensions on HF-DIMS layer (LINE + TEXT)
  dxf.setCurrentLayerName("HF-DIMS");
  for (const d of layout.dimensions) {
    dxf.addLine(pt(d.x1, d.y1), pt(d.x2, d.y2));

    const midX = (d.x1 + d.x2) / 2;
    const midY = (d.y1 + d.y2) / 2;
    dxf.addText(pt(midX, midY + 1), 2, d.label);
  }

  // Title block on HF-TITLEBLOCK layer
  dxf.setCurrentLayerName("HF-TITLEBLOCK");
  const tbX = 15;
  const tbY = 10;
  const tbW = layout.paperWidth - 30;
  const tbH = 35;

  // Title block border
  dxf.addLine(pt(tbX, tbY), pt(tbX + tbW, tbY));
  dxf.addLine(pt(tbX + tbW, tbY), pt(tbX + tbW, tbY + tbH));
  dxf.addLine(pt(tbX + tbW, tbY + tbH), pt(tbX, tbY + tbH));
  dxf.addLine(pt(tbX, tbY + tbH), pt(tbX, tbY));

  dxf.setCurrentLayerName("HF-TEXT");
  dxf.addText(pt(tbX + 5, tbY + tbH - 8), 5, "HARMONY FIRE");
  dxf.addText(pt(tbX + 5, tbY + tbH - 14), 2.5, "Fire Protection Specialists");
  dxf.addText(pt(tbX + tbW * 0.4, tbY + tbH - 8), 2.5, `Ref: ${options.plan_reference}`);
  dxf.addText(pt(tbX + tbW * 0.4, tbY + tbH - 13), 2.5, `Floor: ${options.floor_label}`);
  dxf.addText(pt(tbX + tbW * 0.4, tbY + tbH - 18), 2.5, `Scale: ${options.scale}`);
  dxf.addText(pt(tbX + tbW * 0.4, tbY + tbH - 23), 2.5, `Paper: ${options.paper_size}`);

  if (options.project_name) {
    dxf.addText(pt(tbX + tbW * 0.75, tbY + tbH - 8), 2.5, `Project: ${options.project_name}`);
  }

  dxf.addText(
    pt(tbX + tbW * 0.75, tbY + tbH - 13),
    2.5,
    `Date: ${new Date().toLocaleDateString("en-GB")}`
  );
  dxf.addText(
    pt(tbX + tbW * 0.75, tbY + tbH - 28),
    2,
    "Generated by hf.bluebook"
  );

  // Page border on HF-TITLEBLOCK
  dxf.setCurrentLayerName("HF-TITLEBLOCK");
  dxf.addLine(pt(5, 5), pt(layout.paperWidth - 5, 5));
  dxf.addLine(pt(layout.paperWidth - 5, 5), pt(layout.paperWidth - 5, layout.paperHeight - 5));
  dxf.addLine(pt(layout.paperWidth - 5, layout.paperHeight - 5), pt(5, layout.paperHeight - 5));
  dxf.addLine(pt(5, layout.paperHeight - 5), pt(5, 5));

  return dxf.stringify();
}
